### PR TITLE
2023 06 26

### PR DESCRIPTION
**Pull request by PonteIneptique**
Hey :)
This is a fix for two recent issues:
- It gives the ability to document line-pair datasets
- It gives the ability to describe dataset that were the result of automatic alignment.

It should fix:
- #19
- #20

It should help for:
- https://github.com/HTR-United/htr-united/pull/102
- https://github.com/HTR-United/htr-united/issues/118

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Once merge, it needs to be added in the form.

**Comment by alix-tz** [comment]
Hello! It looks good to me!

I'm wondering if there could be another way to implement the `"automatically-aligned"` component to prepare the way for other flags, such as "silver dataset". 


But, since this would require further discussions, I think it's ok to keep it for a future version.

**Comment by PonteIneptique** [comment]
I thought about a flag dict property, but it feels like it would be a lot
of pre-over-engineering right now.

**Comment by alix-tz** [comment]
Ok! I suggest we merge to create this new version, then we can work on the integration on the website!

**Pull request merged**
